### Create Account -- (201) Created
POST {{base_url}}/customers/{{customer_id}}/accounts
Content-Type: application/json
Authorization: {{api_key}}

{
  "externalReference": "my_reference -1-",
  "currency": "EUR",
  "productCode": "O1200001"
}

### Create Account -- (400) Bad Request
POST {{base_url}}/customers/{{customer_id}}/accounts
Content-Type: application/json
Authorization: {{api_key}}

{
  "externalReference": "my_reference -1-",
  "currency": "EUR",
  "productCode": null
}
